//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incremental.Kick.Web.UI.Pages.Community {
    
    
    /// <summary>
    /// WhoIsOnline class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class WhoIsOnline {
        
        /// <summary>
        /// UserOnlineList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Incremental.Kick.Web.Controls.UserList UserOnlineList;
        
        /// <summary>
        /// UserTodayList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Incremental.Kick.Web.Controls.UserList UserTodayList;
    }
}
