//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incremental.Kick.Web.UI.Pages.Story {
    
    
    /// <summary>
    /// View class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class View {

        protected Incremental.Kick.Web.Controls.StorySummary StorySummary;
        protected Incremental.Kick.Web.Controls.CommentList CommentList;
        protected Incremental.Kick.Web.UI.Controls.AddComment AddComment;
        protected Incremental.Kick.Web.Controls.KickForStoriesMenu KickMenu;
    }
}
